/** WebP + PNG image-set for public wallpapers (generated by scripts/optimize-images.mjs). */
export function wallpaperImageSet(pngPath: string): string {
  const webpPath = pngPath.replace(/\.png$/i, ".webp");
  return `image-set(url("${webpPath}") type("image/webp"), url("${pngPath}") type("image/png"))`;
}

export const WALLPAPERS = {
  hero: "/hero-bg.png",
  contact: "/contact.png",
  partners: "/partners.png",
  services: "/service-wallpaper.png",
  caseStudies: "/service-wallpaper.png",
} as const;
